name: Npc_Creator
version: '1.0-SNAPSHOT'
main: iamtahoma.npc_creator.Npc_Creator
api-version: 1.19
authors: [IamTahoma]
depend: [Citizens]
commands:
  create_npc:
    description: Crea un NPC en la ubicación actual del jugador.
    usage: /create_npc [nombre]
  delete_npc:
    description: Elimina un NPC Segun su nombre.
    usage: /delete_npc [nombre]
  list_npc:
    description: Muestra la lista de NPCs creados